# Generated by Django 3.2.9 on 2021-12-20 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0006_auto_20211220_1544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='street_address',
            new_name='street',
        ),
    ]
